---
galaxy_info:
  role_name: neovim
  author: marcus_grant
  description: |
    A role to clone a git-controlled directory containing neovim dotfiles,
    then linking them and being able to pull new changes in the future.
  issue_tracker_url: https://github.com/marcus-grant/ansible-collection-dotfiles/issues
  license: GPL-2.0-or-later

  min_ansible_version: '2.1'

  platforms:
    - name: Debian
      versions:
        - 10
        - 11
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: Archlinux
      versions:
        - all

  galaxy_tags:
    - dotfiles
    - dots
    - git
    - neovim
    - nvim
    - config
    - shell

# dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
