---
# defaults file for tmux
tmux_config_dir: ~/.config/tmux
tmux_conf_path: "{{ tmux_config_dir }}/.tmux.conf"
tmux_tpm_enable: true
tmux_git_repo: ''
tmux_git_version: HEAD
tmux_git_force: false
tmux_git_backup: true
