---
# tasks file for git
- name: Install git and extra git-related packages
  ansible.builtin.package:
    name: "{{ git_package }}"
    state: present
  loop_control: {loop_var: git_package}
  loop: "{{ ['git'] | union(git_extra_packages | default([])) }}"

- name: Set git config for user
  community.general.git_config:
    name: "{{ git_cfg_item.prop }}"
    scope: global
    state: present
    value: "{{ git_cfg_item.value }}"
  loop_control: {loop_var: git_cfg_item}
  loop:
    - {prop: init.defaultBranch, value: "{{ git_default_branch }}"}
    - {prop: user.name, value: "{{ git_user_name }}"}
    - {prop: user.email, value: "{{ git_user_email }}"}
    - {prop: pull.rebase, value: "{{ git_pull_rebase | ternary('true', 'false', omit) }}"}
